### ISSUE TITLE
ValueError: Variable RNNLM/training/RNNLM/model_1/rnn_outputs/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by dmitrinesterenko** [dmitrinesterenko/cs224d#16]
training
Traceback (most recent call last):
  File "q3_RNNLM.py", line 462, in <module>
    test_RNNLM()
  File "q3_RNNLM.py", line 413, in test_RNNLM
    gen_model = RNNLM_Model(gen_config)
  File "q3_RNNLM.py", line 251, in __init__
    self.train_step = self.add_training_op(self.calculate_loss)
  File "q3_RNNLM.py", line 228, in add_training_op
    train_op = tf.train.AdamOptimizer(self.config.lr).minimize(loss)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 289, in minimize
    name=name)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 403, in apply_gradients
    self._create_slots(var_list)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/adam.py", line 117, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 647, in _zeros_slot
    named_slots[var] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 123, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 101, in create_slot
    return _create_slot_var(primary, val, '')
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/dmitri/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 657, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable RNNLM/training/RNNLM/model_1/rnn_outputs/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by dmitrinesterenko** [comment]
Related reading
https://stackoverflow.com/questions/34592172/about-names-of-variable-scope-in-tensorflow
https://github.com/tensorflow/tensorflow/issues/1325

**Comment by dmitrinesterenko** [comment]
This has to do with me instantiating rnn_outputs as a tf.Variable that is of size num_steps x batch_size x hidden_size when I should be using rnn_outputs as an array with num_steps elements each of which is of shape batch_size x hidden_size.

**Comment by dmitrinesterenko** [comment]
Solved the other issue of self.initial_state by using a non variable (a local instance variable?) for self.initial_state 
```
self.initial_state = tf.zeros((self.config.batch_size, self.config.hidden_size))
h_t = self.initial_state
```
To me the difficulty of tensorflow remains in correctly choosing which variables should be initialized with tf.get_variable() -- all variables that you wish to share, the shared context
tf.Variable() -- errr not sure when these really should be used
variable = tf.zeros() -- whenever you want a local variable without much fuss (again not sure exactly when that is but basically whenever a variable does not need to go into the shared context).
